# Generated by Django 4.2.6 on 2023-10-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=15)),
                ('regimen', models.CharField(max_length=20)),
                ('entidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_prestador', models.CharField(max_length=250)),
                ('nit', models.CharField(max_length=15)),
                ('naturaleza', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
