# Generated by Django 4.2.6 on 2023-10-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=15)),
                ('regimen', models.CharField(max_length=20)),
                ('entidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_prestador', models.CharField(max_length=250)),
                ('nit', models.CharField(max_length=15)),
                ('naturaleza', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name_emergencia', models.CharField(max_length=50)),
                ('contacto_emergencia', models.CharField(max_length=10)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.eps')),
            ],
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respiratoria', models.BooleanField(default=False)),
                ('traumatismos', models.BooleanField(default=False)),
                ('quemaduras', models.BooleanField(default=False)),
                ('perdida', models.BooleanField(default=False)),
                ('hemorragia', models.BooleanField(default=False)),
                ('trabajo_parto', models.BooleanField(default=False)),
                ('abuso_sexual', models.BooleanField(default=False)),
                ('signos_vitales', models.BooleanField(default=False)),
                ('convulsivo', models.BooleanField(default=False)),
                ('deficiencia_respiratoria', models.BooleanField(default=False)),
                ('crisis_hipertensiva', models.BooleanField(default=False)),
                ('fiebre', models.BooleanField(default=False)),
                ('vertigo', models.BooleanField(default=False)),
                ('respiratoria_leve', models.BooleanField(default=False)),
                ('tos_congestion', models.BooleanField(default=False)),
                ('dolor_cabeza_cronico', models.BooleanField(default=False)),
                ('triage_calculado', models.CharField(default=0, max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('nombre_completo', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('sexo', models.CharField(max_length=10)),
                ('nombre_contacto_emergencia', models.CharField(max_length=100)),
                ('numero_contacto_emergencia', models.CharField(max_length=20)),
                ('direccion_residencia', models.TextField()),
                ('acceso_ubicacion_habilitado', models.BooleanField()),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('tipo_sangre', models.TextField(default='Tipo A', max_length=5)),
                ('medicamentos_alergicos', models.TextField(blank=True)),
                ('eps', models.ForeignKey(default='EPS006', on_delete=django.db.models.deletion.CASCADE, to='users.eps')),
            ],
        ),
    ]
