# Generated by Django 4.2.6 on 2023-10-19 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, null=True)),
                ('nit', models.CharField(max_length=15, null=True)),
                ('regimen', models.CharField(max_length=20, null=True)),
                ('entidad', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.eps'),
        ),
    ]
