# Generated by Django 4.2.6 on 2023-10-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_eps_alter_user_eps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eps',
            name='id',
        ),
        migrations.AlterField(
            model_name='eps',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
