# Generated by Django 4.2.6 on 2023-10-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_eps_id_alter_eps_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eps',
            name='entidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eps',
            name='nit',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='eps',
            name='regimen',
            field=models.CharField(max_length=20),
        ),
    ]
