# Generated by Django 3.2.22 on 2023-10-22 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_created_at_alter_eps_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('eps', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('nombre_contacto_emergencia', models.CharField(max_length=100)),
                ('numero_contacto_emergencia', models.CharField(max_length=20)),
                ('direccion_residencia', models.TextField()),
                ('acceso_ubicacion_habilitado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(max_length=5)),
                ('perfil_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='MedicamentoAlergico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('instrucciones_dosificacion', models.CharField(max_length=100)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Alergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario')),
            ],
        ),
    ]
