# Generated by Django 4.2.6 on 2023-10-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_created_at_alter_eps_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nit', models.CharField(max_length=15)),
                ('naturaleza', models.CharField(max_length=15)),
                ('nivel_atencion', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
