# Generated by Django 4.2.6 on 2023-10-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_created_at_alter_eps_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usuario',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
