# Generated by Django 4.2.6 on 2023-10-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ips',
            name='nivel_atencion',
        ),
    ]
