# Generated by Django 3.2.22 on 2023-10-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_alergia_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='perfil_usuario',
        ),
        migrations.RemoveField(
            model_name='medicamentoalergico',
            name='perfil_usuario',
        ),
        migrations.RemoveField(
            model_name='tiposangre',
            name='perfil_usuario',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='medicamentos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='medicamentos_alergicos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_sangre',
            field=models.CharField(default='Tipo A', max_length=5),
        ),
        migrations.DeleteModel(
            name='Alergia',
        ),
        migrations.DeleteModel(
            name='Medicamento',
        ),
        migrations.DeleteModel(
            name='MedicamentoAlergico',
        ),
        migrations.DeleteModel(
            name='TipoSangre',
        ),
    ]
