# Generated by Django 4.2.6 on 2023-10-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_ips_nivel_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ips',
            name='nombre_prestador',
            field=models.CharField(default='NA', max_length=30),
            preserve_default=False,
        ),
    ]
