# Generated by Django 4.2.6 on 2023-10-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_ips_nombre_prestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ips',
            name='nombre_prestador',
            field=models.CharField(max_length=250),
        ),
    ]
