# Generated by Django 3.2.22 on 2023-10-22 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20231021_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.eps'),
        ),
    ]
