# Generated by Django 4.2.6 on 2023-10-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_usuario'),
        ('users', '0009_alter_ips_nombre_prestador'),
    ]

    operations = [
    ]
