# Generated by Django 3.2.22 on 2023-10-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_perfilusuario_eps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_sangre',
            field=models.CharField(default='A', max_length=5),
        ),
    ]
