# Generated by Django 4.2.6 on 2023-10-23 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name_emergencia', models.CharField(max_length=50)),
                ('contacto_emergencia', models.CharField(max_length=10)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.eps')),
            ],
        ),
    ]
