# Generated by Django 3.2.22 on 2023-10-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_perfilusuario_tipo_sangre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_sangre',
            field=models.CharField(default='Tipo A', max_length=5),
        ),
    ]
