# Generated by Django 3.2.22 on 2023-10-22 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_perfilusuario_tipo_sangre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
