# Generated by Django 3.2.22 on 2023-10-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('eps', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('nombre_contacto_emergencia', models.CharField(max_length=100)),
                ('numero_contacto_emergencia', models.CharField(max_length=20)),
                ('direccion_residencia', models.TextField()),
                ('acceso_ubicacion_habilitado', models.BooleanField()),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('tipo_sangre', models.TextField(default='Tipo A', max_length=5)),
                ('medicamentos_alergicos', models.TextField(blank=True)),
            ],
        ),
    ]
