# Generated by Django 3.2.22 on 2023-10-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_perfilusuario_eps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='eps',
            field=models.CharField(max_length=100),
        ),
    ]
