# Generated by Django 3.2.22 on 2023-10-22 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_perfilusuario_eps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='eps',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='eps_aso',
            field=models.ForeignKey(default='EPS006', on_delete=django.db.models.deletion.CASCADE, to='users.eps'),
        ),
    ]
