# Generated by Django 3.2.22 on 2023-10-22 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20231021_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='eps_aso',
            new_name='eps',
        ),
    ]
