# Generated by Django 3.2.22 on 2023-10-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_eps_aso_perfilusuario_eps'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='campo_oculto',
            field=models.CharField(default='Disabled', editable=False, max_length=100),
        ),
    ]
