# Generated by Django 3.2.22 on 2023-10-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20231022_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='perfil_completo',
        ),
    ]
