# Generated by Django 3.2.22 on 2023-10-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_perfilusuario_perfil_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='perfil_completo',
        ),
    ]
