# Generated by Django 3.2.22 on 2023-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_perfilusuario_perfil_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='numero_identificacion',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
