# Generated by Django 3.2.22 on 2023-10-22 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20231022_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('temperatura', models.FloatField()),
                ('presion', models.CharField(max_length=10)),
                ('frecuencia_cardiaca', models.CharField(max_length=10)),
                ('frecuencia_respiratoria', models.CharField(max_length=10)),
                ('saturacion_oxigeno', models.CharField(max_length=10)),
                ('nivel_dolor', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
