# Generated by Django 3.2.22 on 2023-10-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20231022_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triage',
            name='id',
        ),
        migrations.AlterField(
            model_name='triage',
            name='fecha',
            field=models.DateField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
