# Generated by Django 3.2.22 on 2023-10-23 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_triage_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triage',
            name='abuso_sexual',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='convulsivo',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='crisis_hipertensiva',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='deficiencia_respiratoria',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='dolor_cabeza_cronico',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='fiebre',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='hemorragia',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='perdida',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='quemaduras',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='respiratoria_leve',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='signos_vitales',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='tos_congestion',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='trabajo_parto',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='traumatismos',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='triage_calculado',
        ),
        migrations.RemoveField(
            model_name='triage',
            name='vertigo',
        ),
    ]
