# Generated by Django 3.2.22 on 2023-10-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_triage_triage_calculado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='triage',
            unique_together={('usuario', 'fecha')},
        ),
    ]
