# Generated by Django 3.2.22 on 2023-10-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20231022_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='traumatismos',
            field=models.BooleanField(default=False),
        ),
    ]
