# Generated by Django 3.2.22 on 2023-10-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_triage_traumatismos'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='abuso_sexual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='convulsivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='crisis_hipertensiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='deficiencia_respiratoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='dolor_cabeza_cronico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='fiebre',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='hemorragia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='perdida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='quemaduras',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='respiratoria_leve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='signos_vitales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='tos_congestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='trabajo_parto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='vertigo',
            field=models.BooleanField(default=False),
        ),
    ]
