# Generated by Django 4.2.6 on 2023-10-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user'),
        ('users', '0040_ips'),
    ]

    operations = [
    ]
