# Generated by Django 4.2.6 on 2023-11-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cita', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.CharField(max_length=5)),
                ('ips', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.ips')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.usuario')),
            ],
        ),
    ]
