# Generated by Django 4.2.6 on 2023-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_citas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='fecha',
            field=models.CharField(max_length=5),
        ),
    ]
